Add Development Process Guidelines base
morganey-lang/organization pull request #32
Opened 2016-11-19 15:28 UTC by rexim

Split #7

2016-11-20 05:00 UTC, ForNeVeR requested changes
I'm not sure if we want this merged with all these "TBD" marks. It has no actual value without at least some of them filled in.

2016-11-20 05:00 UTC, ForNeVeR commented on DevelopmentProcess.md
> +So, before contributing anything to any of the [@morganey-lang]'s projects, ask a corresponding Project Leader about development process details. See [Projects.md](Projects.md) for the full list of [
Probably add a line addressed to project leader, e.g. "if you're a project leader, consider following these practices with your development".

2016-11-20 05:00 UTC, ForNeVeR commented on DevelopmentProcess.md
> +f
I think that's a typo.

2016-11-20 17:48 UTC, rexim commented on DevelopmentProcess.md
> +f
Fxd

2016-11-20 17:48 UTC, rexim commented on DevelopmentProcess.md
> +So, before contributing anything to any of the [@morganey-lang]'s projects, ask a corresponding Project Leader about development process details. See [Projects.md](Projects.md) for the full list of [
Add a small notice about that

2016-11-20 17:57 UTC, rexim commented
> I'm not sure if we want this merged with all these "TBD" marks. It has no actual value without at least some of them filled in.

Once this PR is approved I'm gonna fill them with corresponding issue numbers

2016-11-21 04:18 UTC, ForNeVeR approved these changes
Okay then. LGTM!

2016-11-21 17:26 UTC, rexim commented
@ForNeVeR thanks for the review!

2016-11-21 17:26 UTC, merged